import Layout from "../components/layout";
import Head from 'next/head'

export default function projects() {
    return (
        <Layout>
            <Head>
                <title>NextJs 프로젝트</title>
                <meta name="description" content="Generated by create next app" />
                <link rel="icon" href="/favicon.ico" />
            </Head>

            <h1>프로젝트!</h1>
        </Layout>
    );
}